### PR TITLE
Added Solution For FairCandySwap

### PR DESCRIPTION
**Pull request by Soham182001**
### What have you Changed(must)
Added solution to problem no. 888. Fair Candy Swap in C++

### Issue no.(must) - #868
.
### Self Check(Tick After Making pull Request)

- [X] This issue was assigned to me if not it will be marked as spam.
- [X] My file is in the proper folder
- [X] I am following clean code and Documentation.
- [X] I have added the title and what program will do first in the file
- [X] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Add some comments at the start of code to explain what your program is doing.
Also Remove the Binary file .DS_Store we only need the .cpp file

**Comment by SSKale1** [comment]
@Soham182001 Please make the requested changes asap. Or we'll have to close this issue.

**Comment by Soham182001** [comment]
Ok I will correct it by today.

**Comment by SSKale1** [comment]
👍

**Pull request closed without merging**
