### PR TITLE
Rotate image

### PR DESCRIPTION
**Pull request by jntushar**
### What have you Changed(must) Create 48.RotateImage.java file

Write here what you have changed in the codebase

### Issue no.(must) - #519 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Remove the file 52. N-Queens II and .swp file.

**Comment by SSKale1** [comment]
Make a single pr per issue.

**Comment by jntushar** [comment]
Hey @SSKale1 
I don't know to revert previous commits

**Comment by SSKale1** [comment]
@jntushar you can view the files, from the files changed tab you can view all the individual files and delete or modify them from there. I'm deleting the files here but make the changes in PR #524

**Pull request merged**
