### PR TITLE
Python Programming to Add two numbers

### PR DESCRIPTION
**Pull request by Trombokendu-dev**
# Store input numbers
num1 = input('Enter first number: ')
num2 = input('Enter second number: ')

# Add two numbers
sum = float(num1) + float(num2)

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

**Output**
Enter first number: 1.5
Enter second number: 6.3
The sum of 1.5 and 6.3 is 7.8

### CODE REVIEW

**Comment by SSKale1** [comment]
Please go through the [Contribution Guidelines](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

**Comment by Omomom2011** [comment]
Running Sum of 1d array Solution.py ...

**Comment by Omomom2011** [comment]
#1488

**Comment by Omomom2011** [comment]
[# Python implementation of substituting a   # specific text pattern in a string using regex     # importing regex module  import re     # Function to perform  # operations on the strings  def substitutor():             # a string variable      sentence1 = "It is raining outside."            # replacing text 'raining' in the string       # variable sentence1 with 'sunny' thus      # passing first parameter as raining      # second as sunny, third as the       # variable name in which string is stored      # and printing the modified string      print(re.sub(r"raining", "sunny", sentence1))             # a string variable      sentence2 = "Thank you very very much."            # replacing text 'very' in the string       # variable sentence2 with 'so' thus       # passing parameters at their       # appropriate positions and printing       # the modified string      print(re.sub(r"very", "so", sentence2))     # Driver Code:   substitutor() ](https://github.com/Omomom2011/rajatkb.git) 
Ok

**Pull request closed without merging**
