### PR TITLE
1510 | Stone Game IV | C++

### PR DESCRIPTION
**Pull request by alpha-k911**
### What have you Changed(must)
Added 1510. Stone Game IV (https://leetcode.com/problems/stone-game-iv/)
### Issue no.(must) - #1167 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by alpha-k911** [comment]
@swaingotnochill @JOKUE2002 @SSKale1

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Add some comments to explain what your program is doing.

**Comment by alpha-k911** [comment]
fine i will add

**Comment by alpha-k911** [comment]
I have added the **approach** in the top

**Comment by alpha-k911** [comment]
@SSKale1 @JOKUE2002 @swaingotnochill

**Comment by alpha-k911** [comment]
@shouvikch97

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
