### PR TITLE
Added C++ solution for 1588. Sum of All Odd Length Subarrays

### PR DESCRIPTION
**Pull request by rituraj735**
### What have you Changed(must)
Added C++ solution for 1588. Sum of All Odd Length Subarrays

Write here what you have changed in the codebase

### Issue no.(must) - # 569

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Delete the file not a part of this issue. 1589. in this case.

**Comment by rituraj735** [comment]
> Delete the file not a part of this issue. 1589. in this case.

The File 1589 was successfully deleted

**Comment by rituraj735** [comment]
> Delete the file not a part of this issue. 1589. in this case.

Please merge.

**Comment by SSKale1** [comment]
@rituraj735 You've deleted both the files there's nothing to merge.

**Comment by rituraj735** [comment]
> @rituraj735 You've deleted both the files there's nothing to merge.

I am sorry for the inconvenience , stupid me. Kindly check.

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
