### PR TITLE
added file 1773 Counting items Matching a rule |CPP  #1682 merge request

### PR DESCRIPTION
**Pull request by vipul-2003**
### What have you Changed(must)

```text
Added solution for the assigned questions and discussed it 
```

### Issue no.(must) - #1682 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as    1773.  Count Items Matching a Rule .cpp

### CODE REVIEW

**Comment by vipul-2003** [comment]
Added file @juhikushwah please review this and merge it ...

**Review by juhikushwah — CHANGES_REQUESTED** [review]
Please add relevant comments to explain what your code is doing.

**Comment by vipul-2003** [comment]
@juhikushwah okk , i will add comments explaining it

**Comment by vipul-2003** [comment]
@juhikushwah , i need your help as the last commit from my side is not merged then how will you edit in my code 

What is the git command to do so ?? 
@juhikushwah

**Comment by juhikushwah** [comment]
@vipul-2003 you can make changes directly to the commit, without creating a new branch or making changes to your local repo. You just need to add comments.

**Comment by vipul-2003** [comment]
> @vipul-2003 you can make changes directly to the commit, without creating a new branch or making changes to your local repo. You just need to add comments.

Now branch is 1 commit back in my local repo as 1 commit is performed , to maintain in my local repo should i have to use git pull command ???

**Comment by juhikushwah** [comment]
@vipul-2003 if you're not getting merge conflicts so far, I would suggest you push your changes.

**Comment by vipul-2003** [comment]
> @vipul-2003 if you're not getting merge conflicts so far, I would suggest you push your changes.
Ok thanks

**Comment by vipul-2003** [comment]
look at the code @juhikushwah  ? Review Code ...

**Review by juhikushwah — APPROVED** [review]

**Pull request merged**
