### PR TITLE
add word break problem solution

### PR DESCRIPTION
**Pull request by vrakr19**
### What have you Changed(must)

Write here what you have changed in cosebase

### Issue no.(must) - #200 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
@vrakr19 You have to mention the issue number in the PR Template

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Add Issue number to the PR.

**Comment by vrakr19** [comment]
@SSKale1 issue no added to pr template

**Comment by vrakr19** [comment]
> Add Issue number to the PR.

@SSKale1 Issue number added.

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
