### PR TITLE
Maximum Product Subarray

### PR DESCRIPTION
**Pull request by ITES7321**
### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #382

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by ITES7321 — COMMENTED** [review]
Changed Name

**Comment by SSKale1** [comment]
You have to mention the issue number in the PR body.

**Comment by ITES7321** [comment]
> You have to mention the issue number in the PR body.

Thanks! I corrected the PR Body!

**Comment by SSKale1** [comment]
@ITES7321 you have to go through the contribution guidelines. You can only make a PR after you've been assigned to that issue. We'll have to close this you can create your own issue.

**Pull request closed without merging**
