### PR TITLE
added by anshuman

### PR DESCRIPTION
**Pull request by shivanshuman021**
### What have you Changed(must)

Added solution to "Length of last word " . Problem link : "https://leetcode.com/problems/length-of-last-word/"

### Issue no.(must) - #531  

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
You have to mention the issue number in the PR body not the PR number.

**Comment by shivanshuman021** [comment]
Is this fine ? Could u explain a little bit on "You have to mention the issue number in the PR body not the PR number." ...
PS.: This is my first pull request.

**Comment by Yashica7** [comment]
@shivanshuman021 
 You've to write the Issue number that u got assigned in the Pull Request body

**Comment by pranav7955** [comment]
> Is this fine ? Could u explain a little bit on "You have to mention the issue number in the PR body not the PR number." ...
> PS.: This is my first pull request.

hi @shivanshuman021 

As i can see there is no issue created for the problem (`58. Length of Last Word
`) you are trying to solve.

So first you will need to create a new issue for this problem.
Github assigns a number to every issue and PR. So, once you create an issue an issue number will be assigned to it.
After that, you need to wait for you to be assigned to that new issue you just created.
Once assigned successfully, you can now create a new PR for that, and while you try to open the PR, the issue number has to be mentioned not the PR number ( Every number assigned to any PR or an issue by Github is unique for a repo.)
___________________________________________________________________________________________________________________

For Example, i can see you already have created an issue `"20 | Valid Parenthesis | C++ g"` Therefore as you can see GitHub has assigned #507 to it. Now that you also have been assigned to this issue you created, you can create a new PR and mention this issue number i.e #507 and `not the number assigned to your PR`.

Hope this helps you understand :)

**Comment by shivanshuman021** [comment]
Thanks a lot @pranav7955 


I've created Issue and Updated the pull request @SSKale1 and have also added explaination to my approach for the code

**Comment by pranav7955** [comment]
> Thanks a lot @pranav7955
> 
> I've created Issue and Updated the pull request @SSKale1 and have also added explaination to my approach for the code

@shivanshuman021  make sure you first get assigned. Only after you get assigned create a new pr for that issue. If you created pr before you get assigned then that pr will be labelled invalid :)

**Review by SSKale1 — APPROVED** [review]

**Comment by SSKale1** [comment]
@shivanshuman021 I've assigned you to the issue this time. Next time onwards make sure you've been assigned to an issue before creating a PR.

**Pull request merged**
