### PR TITLE
9.longest_substring.cpp

### PR DESCRIPTION
**Pull request by VIPUL662**
### What have you Changed(must) 

Write here what you have changed in cosebase
 i have solved problem of finding longest substring in a given string in C++.

### Issue no.(must) - #9

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by VIPUL662** [comment]
i have solved

**Review by SSKale1 — CHANGES_REQUESTED** [review]
The code is perfect just  add the issue number in the PR where it is required.

**Comment by VIPUL662** [comment]
Please tell me where is issue no . Required and how to do.

**Comment by SSKale1** [comment]
@VIPUL662 you need to add the issue # to the PR text right next to "Issue no.(must) -"  Right here where its pointing, there would be an edit option at the three dots at top right of the post.
image

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Remove the issue_no._9 from the name your Earlier commit was perfect.

**Comment by SSKale1** [comment]
Sure

**Comment by VIPUL662** [comment]
Good afternoon sir,
Please lable my contribution as hacktober fest accepted ,it is showing that your contribution is in review period.please sir solve this .

**Comment by VIPUL662** [comment]
Hlo sir please solve my problem 🙏🙏🙏

**Pull request merged**
