### PR TITLE
added the solution for 1351 Count Negative in a sorted array matrix in python

### PR DESCRIPTION
**Pull request by PraneshUlleri**
### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #1303 
#1296 
Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by PraneshUlleri** [comment]
Im sorry, the previous file which I gave for PR also got committed here too
Am I supposed to remove those file, How do I remove those file

**Comment by SSKale1** [comment]
To remove the files you can go to the files changes tab and individually edit and delete each file.

**Comment by SSKale1** [comment]
Which is the Extra file?

**Comment by SSKale1** [comment]
1436 or 1351? And what is the PR # which got merged.

**Comment by PraneshUlleri** [comment]
I gave merge request for previous issue that also got commit in this commit

**Comment by SSKale1** [comment]
What is the issue number Mention it here i'll look into it.

**Comment by PraneshUlleri** [comment]
1436

**Comment by PraneshUlleri** [comment]
there are 3 commits here only 1 was supposed to be

**Review by SSKale1 — APPROVED** [review]

**Comment by SSKale1** [comment]
@PraneshUlleri You can mention multiple issues in the same PR, if you've been assigned to them.

**Pull request merged**
