### PR TITLE
1480 | Running Sum of 1D Array

### PR DESCRIPTION
**Pull request by atingarg1406**
### What have you Changed(must)

Added RunningSumof1DArray Program

### Issue no.(must) - #10 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [1] This issue was assigned to me if not it will marked as spam.
- [2] My file is in proper folder
- [3] I am following clean code and Documentation.
- [4] I have added title and what program will do first in the file
- [5] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
@atingarg1406 Please mention the Issue number in the PR Body.

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Mention the Issue number into the PR Body.

**Review by atingarg1406 — COMMENTED** [review]
Issue #19

**Comment by atingarg1406** [comment]
> Mention the Issue number into the PR Body.

I have done this. I have mentioned the Issue number that is #10 into the PR Body. 
If the task is done then kindly mark as accepted.

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
