### PR TITLE
modified

### PR DESCRIPTION
**Pull request by RachanaKampli**
### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
@RachanaKampli You need to create an issue get assigned to it and only then raise a PR. Please go through the contribution guidelines.

**Comment by RachanaKampli** [comment]
> @RachanaKampli You need to create an issue get assigned to it and only then raise a PR. Please go through the contribution guidelines.

I have changed the file can you go through it once?

**Comment by RachanaKampli** [comment]
I made changes can you check it once?

**Comment by SSKale1** [comment]
@RachanaKampli Problem 543 already exists in the codebase. And you've to first make an issue get assigned to it and then raise a PR.

**Comment by RachanaKampli** [comment]
Sorry actually issue number is 512

**Comment by SSKale1** [comment]
#512 I’ll check

**Comment by SSKale1** [comment]
Okay in this case you’ll have to change the file name to the proper format starting with the problem number on LC

**Comment by SSKale1** [comment]
Rename to 1365. ......

**Comment by RachanaKampli** [comment]
I have renamed it.

**Comment by SSKale1** [comment]
You created a new PR. You had to make changes here. I'm doing it myself for now.

**Pull request merged**
