### PR TITLE
Armstrong | C++ | Merge request for issue #1612 

### PR DESCRIPTION
**Pull request by vipul-2003**
### What have you Changed(must)

```text
Added new code 
```

### Issue no.(must) - # 1612

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by vipul-2003** [comment]
hi @juhikushwah , i have done my best to add the code as they leetcode shows need subscription to view the question , but anyways look at the code 
thanks ❤️

**Comment by vipul-2003** [comment]
corrected the file name

**Comment by vipul-2003** [comment]
Review the changes @juhikushwah

**Comment by vipul-2003** [comment]
file renamed , but having some extra commits 😅 , i'm  trying stash command to merge these commits  but unsuccessful

**Comment by vipul-2003** [comment]
@juhikushwah , now the file is renamed  have a look at that ...

**Review by juhikushwah — CHANGES_REQUESTED** [review]
@vipul-2003 you've merged c++ code of this problem with python code of another problem.  I'm not sure how you are pushing your changes every time, but having so many commits for small issues can be very messy. I would suggest you create another merge request and before pushing your changes, ensure that the **file name is in the correct format**. Also, please read the contributions guideline so you can make PRs efficiently. I'm closing this PR for now.

**Pull request closed without merging**
