### PR TITLE
Q.143: Reorder List

### PR DESCRIPTION
**Pull request by Himalay12**
### What have you Changed(must)

Added solution for Q.143: Reorder List.

### Issue no.(must) - #1238

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by Himalay12** [comment]
I read the guidelines an did the changes if it require changes please comment here.

**Comment by Yashica7** [comment]
since this is your first time, we'll be accepting your pull request, from next time, make sure you are assigned to that code by the Maintainers of this repository and only then submit a PR

**Comment by Himalay12** [comment]
Thank you. I will do it from next time.
There is two more pull request from me.

**Comment by Himalay12** [comment]
if you can merge it then i will be thankful.

**Comment by Himalay12** [comment]
If you will merge it then i will be able to complete hactoberfest 2020.

**Pull request merged**
