### PR TITLE
Create 504. Base7.cpp

### PR DESCRIPTION
**Pull request by pstreemaze**
### What have you Changed(must)
Wrote a code

Write here what you have changed in the codebase

### Issue no.(must) - #1120 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x ] This issue was assigned to me if not it will be marked as spam.
- [ x] My file is in the proper folder
- [x ] I am following clean code and Documentation.
- [x ] I have added the title and what program will do first in the file
- [x ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Place your file in the correct directory and add some comments to explain what your program is doing.

**Comment by pstreemaze** [comment]
Can you please help me how to change the directory, I commented the code. @SSKale1 can you please change the directory? This pull request is important for my hacktober ;-;

**Comment by SSKale1** [comment]
Just rename to C++/<your file name>.

**Comment by SSKale1** [comment]
I'm doing it myself, np

**Review by SSKale1 — APPROVED** [review]

**Comment by pstreemaze** [comment]
Thank you so much!! :)

**Comment by pstreemaze** [comment]
@SSKale1 I created this PR in october- why the website is showing pending even after the merge? The website quotes for this PR as ---;"Pending
Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it."

**Pull request merged**
