### PR TITLE
Added solution to problem #326 Power of Three 

### PR DESCRIPTION
**Pull request by devesh-badal**
### What have you Changed(must)

added the solution of 326, Power of Three problem in C++ folder.  

### Issue no.(must) - #38

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
The code is alright. Just add some comments at the start to describe what the program does.
Also mention the issue number in the PR. !!IMPORTANT!!

**Comment by devesh-badal** [comment]
@SSKale1  done!

**Comment by SSKale1** [comment]
@devesh-badal you still need to add the comments

**Review by devesh-badal — COMMENTED** [review]
comments added

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
