### PR TITLE
Added solution to 1295.Find Numbers with Even Number of Digits

### PR DESCRIPTION
**Pull request by Largetable**
### What have you Changed(must)
Added a solution
Write here what you have changed in codebase

### Issue no.(must) - #294

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Review by SSKale1 — APPROVED** [review]
Just add some comments to explain what your code does. and rename the file according to the format mentioned in the PR Body.

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Comments and Renaming the file.

**Comment by Largetable** [comment]
@SSKale1 could you please add hacktoberfest-accepted label when you accept my pull request?

**Review by SSKale1 — APPROVED** [review]

**Comment by SSKale1** [comment]
@Largetable The PR is automatically accepted for hacktoberfest when it is merged into the codebase. No need to worry about labels here.

**Comment by Largetable** [comment]
@SSKale1 oh yes you are right, hacktoberfest is included in this repo's topics, thank you!

**Pull request merged**
