### PR TITLE
24. Swap Nodes in Pairs

### PR DESCRIPTION
**Pull request by kajal-puri**
### What have you Changed(must)

Added new code 
### Issue no.(must) - #1310 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by kajal-puri** [comment]
@SSKale1 let me know if there is any changes to be made.

**Review by Yashica7 — CHANGES_REQUESTED** [review]
Remove the extra files and add a description of your code

**Comment by kajal-puri** [comment]
@Yashica7 I've made the suggested changes. Can you check and let me know?

**Comment by kajal-puri** [comment]
@Yashica7 Made the changes, please have a look and let me know!

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
