### PR TITLE
pr #1684 | perfect valid square leetcode solution

### PR DESCRIPTION
**Pull request by vipul-2003**
### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #1684 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as  **367 ValidPerfectSquare.cpp**

### CODE REVIEW

**Comment by vipul-2003** [comment]
review the code @juhikushwah 👍

**Comment by juhikushwah** [comment]
@vipul-2003 I see a merge conflict. Please resolve it. The only option I have from my end is to close this PR. I think, you've used the same branch that you used for the previous issue. Please look into it!

**Comment by vipul-2003** [comment]
> @vipul-2003 I see a merge conflict. Please resolve it. The only option I have from my end is to close this PR. I think, you've used the same branch that you used for the previous issue. Please look into it!

no i have created a ne branch called "brnach2"  and then commit the changes

**Comment by vipul-2003** [comment]
is there any option to correct the changes ??

**Comment by vipul-2003** [comment]
please don't close it until i told you i am working and exploring more to reslove it 
 @juhikushwah

**Comment by vipul-2003** [comment]
i think i have to check a new one at it is to much complicated .....

**Comment by vipul-2003** [comment]
i don't know but some how i have resolved the issue , now every things seems good , have a look at code @juhikushwah

**Review by juhikushwah — APPROVED** [review]

**Pull request merged**
