### PR TITLE
Create 1305. All Elements in Two Binary Search Trees

### PR DESCRIPTION
**Pull request by Himalay12**
### What have you Changed(must)

Write here what you have changed in the codebase

### Issue no.(must) - #

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [ ] My file is in the proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [ ] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
@Himalay12 you have to mention the issue number in the PR Body.

**Comment by Himalay12** [comment]
i have added new file file.

**Comment by Himalay12** [comment]
so i don't understand what to write in issue.

**Comment by SSKale1** [comment]
@Himalay12 Please do go through the Contribution guidelines for this project. There's a complete workflow and format for everything.

**Comment by Himalay12** [comment]
can you share the link to guideline.

**Comment by SSKale1** [comment]
You can find in it the previous comment. here it is anyway. https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md

**Comment by Himalay12** [comment]
thank you. i will go thorugh it and update the require changes.

**Comment by SSKale1** [comment]
Do not make changes to this PR. It has now been closed. Create a new issue and get assigned to it, then create a PR while following the proper format.

**Comment by Himalay12** [comment]
ok

**Pull request closed without merging**
