### PR TITLE
change C++/198. HouseRobber.cpp code 

### PR DESCRIPTION
**Pull request by Piyush228**
### What have you Changed(must)

code of C++/198( HouseRobber.cpp) does not run in all test cases 

### Issue no.(must) - #333 
Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x]  I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
@Piyush228 you can create another issue for refactoring the code.

**Comment by Piyush228** [comment]
sir i saw a code of  HouseRobber.cpp and that code was wrong,
this was the correct code of problem HouseRobber
https://github.com/SHY-Corp/LeetCode-Solutions/pull/770/commits/a05f8bd95d1cd291d40c78ceeedd44f0f1d55648
dont see commented  see code :)
thank & regards

**Comment by SSKale1** [comment]
@Piyush228 your code is good but we’ve got to adhere to the contribution guidelines. You can create an issue for refactoring the code for the specific problem. We’ll assign it to you and then you can submit a proper PR following the template. You can go through the contribution guidelines to make things clear.

**Comment by Piyush228** [comment]
Yes I created an issue Please assign me Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [SHY-Corp/LeetCode-Solutions] change C++/198. HouseRobber.cpp code  (#770)From: Shantanu Kale To: SHY-Corp/LeetCode-Solutions CC: Piyush228 <1piyush1verma@gmail.com>,Mention 

@Piyush228 your code is good but we’ve got to adhere to the contribution guidelines. You can create an issue for refactoring the code for the specific problem. We’ll assign it to you and then you can submit a proper PR following the template. You can go through the contribution guidelines to make things clear.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/SHY-Corp/LeetCode-Solutions/pull/770#issuecomment-713047872",

"url": "https://github.com/SHY-Corp/LeetCode-Solutions/pull/770#issuecomment-713047872",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Pull request closed without merging**
