### PR TITLE
Leetcode Bit Manipulation answer added

### PR DESCRIPTION
**Pull request by champ96k**
### What have you Changed(must) -
  Added the below question answer
                  - 201. Bitwise AND of Numbers Range #1278
                  - 268. Missing Number #1279
                  - 389. Find the Difference #1281
                  - 461. Hamming Distance #1282
                  - 476. Number Complement #1284
                  - 693. Binary Number with Alternating Bits #1285

### Issue no.(must) -   #1278, #1279 , #1281, #1282, #1284, #1285

Pr will be close and marked as spam. If the issue number not found or the issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [x] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by champ96k** [comment]
Bit manipulation answer added

**Comment by champ96k** [comment]
#1278

**Comment by champ96k** [comment]
This pull request contains the answer to the below question
 
 - [x] 201. Bitwise AND of Numbers Range  #1278 
 - [x] 268. Missing Numbe
 - [x] 389. Find the Difference
 - [x] 461. Hamming Distance
 - [x] 476. Number Complement
 - [x] 693. Binary Number with Alternating Bits

**Review by SSKale1 — APPROVED** [review]

**Comment by champ96k** [comment]
thank you so much

**Comment by SSKale1** [comment]
There were a lot of changes to be made, but I did them myself this time. Just make sure you remove all the temporary files before submitting a PR.

**Pull request merged**
