### PR TITLE
[ADD] Added PrimeFactors solution already refactored.

### PR DESCRIPTION
**Pull request by colmanfranco**
### What have you Changed(must)

Added the PrimeFactors Kata solution where it should return an array with all the prime factors of a given number.

### #420 - #

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will be marked as spam.
- [x] My file is in the proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added the title and what program will do first in the file
- [x] I have named the file as (Problem #). (Problem Title(in Camel Case)).(extension)
      ex. 2. AddToNumbers.py

### CODE REVIEW

**Comment by SSKale1** [comment]
The content inside is blank.

**Comment by colmanfranco** [comment]
sorry, now the changes are reflected. I forgot to push the changes.

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Add some comments at the start of code to explain what your program is doing.

**Comment by colmanfranco** [comment]
Comments added.

**Review by SSKale1 — APPROVED** [review]

**Pull request merged**
